import { useEffect, useRef, useState } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { OrbitControls, PerspectiveCamera } from '@react-three/drei';
import * as THREE from 'three';
import { loadOriginalLevels3D } from '@/game3d/levels3d';
import { bonkRock, isComplete, movePlatform, movePlayer, type Move3D } from '@/game3d/level3dLogic';
import type { Level3D, Platform3D, Position3D, Rock3D } from '@/game3d/level3d';
import './Dinodash3D.css';

const moves:Array<[string,Move3D]>=[['↑','up'],['↓','down'],['←','left'],['→','right']];
const S=1;

function Dino({player,selected,heading,celebrate}:{player:Position3D;selected:boolean;heading:number;celebrate:boolean}){
 const g=useRef<THREE.Group>(null),body=useRef<THREE.Group>(null),tail=useRef<THREE.Mesh>(null),eyeL=useRef<THREE.Mesh>(null),eyeR=useRef<THREE.Mesh>(null);const prev=useRef(new THREE.Vector3(player.x,player.height+.35,player.y));
 useFrame(({clock},dt)=>{if(!g.current||!body.current)return;const t=clock.getElapsedTime();const target=new THREE.Vector3(player.x*S,player.height+.35,player.y*S);const dist=g.current.position.distanceTo(target);g.current.position.lerp(target,1-Math.exp(-dt*12));const moving=dist>.02;const step=moving?Math.sin(t*15):0;body.current.position.y=THREE.MathUtils.damp(body.current.position.y,Math.abs(step)*.045+(celebrate?Math.abs(Math.sin(t*8))*.1:0),14,dt);body.current.rotation.z=THREE.MathUtils.damp(body.current.rotation.z,moving?step*.06:celebrate?Math.sin(t*7)*.12:0,12,dt);g.current.rotation.y=THREE.MathUtils.damp(g.current.rotation.y,heading,14,dt);if(tail.current)tail.current.rotation.y=THREE.MathUtils.damp(tail.current.rotation.y,Math.sin(t*8)*.2+(moving?step*.1:0),12,dt);const blink=Math.sin(t*1.9)>0.986;[eyeL.current,eyeR.current].forEach(e=>e&&(e.scale.y=THREE.MathUtils.damp(e.scale.y,blink?.08:1,40,dt)));prev.current.copy(g.current.position)});
 return <group ref={g}><group ref={body}><mesh castShadow position={[0,.2,0]}><capsuleGeometry args={[.2,.3,6,14]}/><meshStandardMaterial color="#74cf72"/></mesh><mesh castShadow position={[0,.5,-.02]}><sphereGeometry args={[.21,24,16]}/><meshStandardMaterial color="#9be58b"/></mesh><mesh ref={eyeL} position={[.075,.54,-.2]}><sphereGeometry args={[.035,12,10]}/><meshStandardMaterial color="#172017"/></mesh><mesh ref={eyeR} position={[-.075,.54,-.2]}><sphereGeometry args={[.035,12,10]}/><meshStandardMaterial color="#172017"/></mesh><mesh ref={tail} position={[0,.2,.27]}><capsuleGeometry args={[.05,.36,5,10]}/><meshStandardMaterial color="#68bd67"/></mesh></group>{selected&&<mesh position={[0,.02,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.29,.37,24]}/><meshBasicMaterial color="#fff0a0"/></mesh>}</group>;
}

function Camera({level,player,topDown}:{level:Level3D;player:Position3D;topDown:boolean}){
 const controls=useRef<any>(null);const {size}=useThree();const max=Math.max(10,Math.max(level.width*S/(2*Math.tan(42*Math.PI/360)*(size.width/Math.max(1,size.height))),level.depth*S/(2*Math.tan(42*Math.PI/360)))*1.18);const center=new THREE.Vector3((level.width-1)*S/2,0,(level.depth-1)*S/2);const dino=new THREE.Vector3(player.x*S,.45,player.y*S);const iso=[dino.x+max*.62,max*.78,dino.z+max*.62] as [number,number,number];const top=[center.x,max*1.12,center.z+.01] as [number,number,number];useFrame((_,dt)=>{if(controls.current&&!topDown){controls.current.target.lerp(dino,Math.min(1,dt*5));controls.current.update()}});return <><PerspectiveCamera makeDefault position={topDown?top:iso} fov={42}/><OrbitControls ref={controls} target={topDown?center:dino} enablePan={false} enableRotate minPolarAngle={0.02} maxPolarAngle={Math.PI/2-.05} enableZoom minDistance={Math.max(4,max*.35)} maxDistance={max} enableDamping dampingFactor={.08}/></>;
}

function Scene({level,player,selected,onSelect,heading,topDown,celebrate}:{level:Level3D;player:Position3D;selected:{type:string;index?:number}|null;onSelect:(s:{type:string;index?:number})=>void;heading:number;topDown:boolean;celebrate:boolean}){
 const cx=(level.width-1)*S/2,cz=(level.depth-1)*S/2;return <><Camera level={level} player={player} topDown={topDown}/><ambientLight intensity={1.25}/><hemisphereLight intensity={1.1} color="#fff9ed" groundColor="#44503e"/><directionalLight position={[7,14,8]} intensity={3.2} castShadow/>
 <group position={[-cx,0,-cz]}>{level.cells.map(c=>c.type==='void'?<mesh key={`v${c.x}-${c.y}`} position={[c.x*S,.02,c.y*S]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.43,20]}/><meshBasicMaterial color="#1c251f"/></mesh>:<group key={`${c.x}-${c.y}`} position={[c.x*S,c.height/2-.03,c.y*S]} onClick={e=>{e.stopPropagation();onSelect({type:'cell',index:c.y*level.width+c.x})}}><mesh castShadow receiveShadow><boxGeometry args={[.9*S,Math.max(.12,c.height),.9*S]}/><meshStandardMaterial color={c.type==='goal'?'#d9a52e':c.type==='wall'?'#8d6f4d':c.type==='start'?'#679a61':'#66736a'} roughness={.9}/></mesh><mesh position={[0,c.height/2+.015,0]}><boxGeometry args={[.78*S,.035,.78*S]}/><meshStandardMaterial color={c.type==='goal'?'#ffe27a':'#879486'}/></mesh></group>)}
 {(level.rocks??[]).map((r:Rock3D,i)=><group key={`r${i}`} position={[r.x*S,r.height/2-.02,r.y*S]} onClick={e=>{e.stopPropagation();onSelect({type:'rock',index:i})}}><mesh castShadow><dodecahedronGeometry args={[.4*S,1]}/><meshStandardMaterial color={r.height===3?'#81786c':r.height===2?'#9b876d':'#b39a78'} roughness={.95}/></mesh>{selected?.type==='rock'&&selected.index===i&&<mesh position={[0,.04,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.43,.49,24]}/><meshBasicMaterial color="#ffe87a"/></mesh>}</group>)}
 {(level.platforms??[]).map((p:Platform3D,i)=><group key={`p${i}`} position={[p.x*S,.13,p.y*S]} onClick={e=>{e.stopPropagation();onSelect({type:'platform',index:i})}}><mesh castShadow><boxGeometry args={[.84*S,.18,.84*S]}/><meshStandardMaterial color={selected?.type==='platform'&&selected.index===i?'#f4cc54':'#d5a74c'}/></mesh><mesh position={[p.dx*.16*S,.13,p.dy*.16*S]} rotation={[0,Math.atan2(p.dy,p.dx),0]}><coneGeometry args={[.14,.36,4]}/><meshStandardMaterial color="#fff0a2"/></mesh></group>)}
 <group position={[player.x*S,player.height+.34,player.y*S]} onClick={e=>{e.stopPropagation();onSelect({type:'dino'})}}><Dino player={player} selected={selected?.type==='dino'} heading={heading} celebrate={celebrate}/></group>
 </group></>;
}

export default function Dinodash3D(){
 const [levels,setLevels]=useState<Level3D[]>([]);const [levelIndex,setLevelIndex]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [player,setPlayer]=useState<Position3D|null>(null);const [rocks,setRocks]=useState<Rock3D[]>([]);const [platforms,setPlatforms]=useState<Platform3D[]>([]);const [selected,setSelected]=useState<{type:string;index?:number}|null>({type:'dino'});const [heading,setHeading]=useState(0);const [topDown,setTopDown]=useState(false);const [completed,setCompleted]=useState(false);
 useEffect(()=>{loadOriginalLevels3D().then(ls=>{setLevels(ls);setLoading(false);setPlayer(ls[0].playerStart);setRocks((ls[0].rocks??[]).map(r=>({...r})));setPlatforms((ls[0].platforms??[]).map(p=>({...p})))}).catch(e=>{setError(e instanceof Error?e.message:'Unable to load levels');setLoading(false)})},[]);
 const level=levels[levelIndex];
 const load=(idx:number)=>{if(!levels[idx])return;const l=levels[idx];setLevelIndex(idx);setPlayer(l.playerStart);setRocks((l.rocks??[]).map(r=>({...r})));setPlatforms((l.platforms??[]).map(p=>({...p})));setSelected({type:'dino'});setHeading(0);setTopDown(false);setCompleted(false)};
 const move=(m:Move3D)=>{if(!level||!player||completed)return;const n=movePlayer(level,player,m,rocks,platforms);if(!n)return;const dx=n.x-player.x,dy=n.y-player.y;setHeading(Math.atan2(dx,dy));setPlayer(n);if(isComplete(level,n)){setCompleted(true);setTimeout(()=>{if(levelIndex<99)load(levelIndex+1)},650)}};
 const cell=selected?.type==='cell'&&selected.index!==undefined?level?.cells[selected.index]:undefined;const selectedRock=selected?.type==='rock'&&selected.index!==undefined?rocks[selected.index]:undefined;const selectedPlatform=selected?.type==='platform'&&selected.index!==undefined?platforms[selected.index]:undefined;
 const onCell=(idx:number)=>{const c=level?.cells[idx];if(!c||!player)return;setSelected({type:'cell',index:idx});const dx=c.x-player.x,dy=c.y-player.y;if(Math.abs(dx)+Math.abs(dy)===1)move(dx===1?'right':dx===-1?'left':dy===1?'down':'up')};
 const bonk=()=>{if(selectedRock&&selected.index!==undefined)setRocks(rs=>bonkRock(rs,selected.index!))};const moveArrow=()=>{if(level&&selectedPlatform&&selected.index!==undefined){const next=movePlatform(level,platforms,selected.index);if(next)setPlatforms(next)}};
 if(loading)return <main className="dinodash3d"><div className="dinodash3d__complete">LOADING ORIGINAL 100 LEVEL CAMPAIGN…</div></main>;
 if(error)return <main className="dinodash3d"><div className="dinodash3d__complete">{error}</div></main>;
 if(!level||!player)return null;
 return <main className="dinodash3d"><header className="dinodash3d__header"><div><strong>DINODASH</strong><span> / 3D</span></div><div>LEVEL {levelIndex+1} / 100</div></header><section className="dinodash3d__stage"><Canvas shadows dpr={[1,2]}><color attach="background" args={["#c5d4c0"]}/><Scene level={level} player={player} selected={selected} onSelect={s=>s.type==='cell'&&s.index!==undefined?onCell(s.index):setSelected(s)} heading={heading} topDown={topDown} celebrate={completed}/></Canvas>{completed&&<div className="dinodash3d__complete">{levelIndex===99?'CAMPAIGN COMPLETE · ALL 100 LEVELS':'LEVEL COMPLETE · NEXT LEVEL'}</div>}</section><section className="dinodash3d__controls"><div className="dinodash3d__selection">{selected?.type==='dino'?'DINO SELECTED':selected?.type==='platform'?'ARROW PLATFORM SELECTED':selected?.type==='rock'?`ROCK SELECTED · ${selectedRock?.height??0} LEVEL`:`CELL ${cell?.x??''},${cell?.y??''}`}</div><div className="dinodash3d__row"><button onClick={()=>setTopDown(v=>!v)}>{topDown?'3D VIEW':'TOP VIEW'}</button><button onClick={()=>setSelected({type:'dino'})}>DINO</button>{selected?.type==='platform'&&<button className="primary" onClick={moveArrow}>MOVE ARROW</button>}{selected?.type==='rock'&&<button className="primary" onClick={bonk} disabled={!selectedRock||selectedRock.height<=0}>HEADBUTT</button>}</div><div className="dinodash3d__dpad">{moves.map(([label,m])=><button key={m} onClick={()=>move(m)}>{label}</button>)}</div><div className="dinodash3d__row"><button onClick={()=>load(Math.max(0,levelIndex-1))}>PREV</button><button onClick={()=>load(levelIndex)}>RESET</button><button onClick={()=>load(Math.min(99,levelIndex+1))}>NEXT</button></div><div className="dinodash3d__hint">{level.hint}</div></section></main>;
}