export type Direction='up'|'right'|'down'|'left';
export type SemanticTile={kind:'void'}|{kind:'floor'}|{kind:'wall'}|{kind:'water'}|{kind:'stone';height:number}|{kind:'breakable';height:number}|{kind:'goal'}|{kind:'start-marker'}|{kind:'arrow';directions:Direction[]}|{kind:'key';color:'red'|'green'}|{kind:'lock';color:'red'|'green'}|{kind:'teleport'}|{kind:'bonus-time'};
export type SemanticLevel={id:number;width:number;height:number;tiles:SemanticTile[][];playerStart:{x:number;y:number};goal:{x:number;y:number}};
const directions:Direction[]=['up','right','down','left'];
/** Exact Phoneage legend; unknown IDs fail closed instead of being guessed. */
export function phoneageTileToSemantic(id:number):SemanticTile{switch(id){case 0:return{kind:'floor'};case 1:return{kind:'wall'};case 2:return{kind:'stone',height:1};case 3:return{kind:'goal'};case 4:return{kind:'water'};case 5:return{kind:'void'};case 6:return{kind:'breakable',height:3};case 7:case 8:case 9:case 10:return{kind:'arrow',directions:[directions[id-7]]};case 11:return{kind:'arrow',directions:['up','down']};case 12:return{kind:'arrow',directions:['left','right']};case 13:return{kind:'arrow',directions:[...directions]};case 14:return{kind:'key',color:'red'};case 15:return{kind:'key',color:'green'};case 16:return{kind:'lock',color:'red'};case 17:return{kind:'lock',color:'green'};case 18:return{kind:'start-marker'};case 19:return{kind:'teleport'};case 20:return{kind:'bonus-time'};default:throw new Error(`Unsupported Phoneage tile ID: ${id}`)}}
export function convertPhoneageLevel(id:number,grid:number[][],playerStart:{x:number;y:number},cavePos:{x:number;y:number}):SemanticLevel{if(grid.length!==11)throw new Error(`Level ${id}: expected 11 rows, got ${grid.length}`);if(grid.some(r=>!Array.isArray(r)||r.length!==20))throw new Error(`Level ${id}: expected 20 columns`);if(playerStart.x<0||playerStart.x>=20||playerStart.y<0||playerStart.y>=11)throw new Error(`Level ${id}: invalid player start`);if(cavePos.x<0||cavePos.x>=20||cavePos.y<0||cavePos.y>=11)throw new Error(`Level ${id}: invalid goal`);return{id,width:20,height:11,tiles:grid.map(r=>r.map(phoneageTileToSemantic)),playerStart,goal:cavePos}}
function trimVoidBorder(level:SemanticLevel,side:'top'|'bottom'|'left'|'right'):SemanticLevel|null{const{tiles,width,height}=level;const removable=side==='top'?tiles[0].every(t=>t.kind==='void'):side==='bottom'?tiles[height-1].every(t=>t.kind==='void'):side==='left'?tiles.every(r=>r[0].kind==='void'):tiles.every(r=>r[width-1].kind==='void');if(!removable)return null;const dx=side==='left'?1:0,dy=side==='top'?1:0;const next=tiles.slice(dy,height-(side==='bottom'?1:0)).map(r=>r.slice(dx,width-(side==='right'?1:0)));return{...level,width:next[0]?.length??0,height:next.length,tiles:next,playerStart:{x:level.playerStart.x-dx,y:level.playerStart.y-dy},goal:{x:level.goal.x-dx,y:level.goal.y-dy}}}
/** Lossless compression: only removes completely void outer rows/columns when possible. Maps that cannot be compressed remain at their authoritative dimensions. */
export function compressSemanticLevel(level:SemanticLevel,maxWidth=16,maxHeight=9):SemanticLevel{let out=level,changed=true;while(changed&&(out.width>maxWidth||out.height>maxHeight)){changed=false;for(const side of ['top','bottom','left','right'] as const){const needed=side==='left'||side==='right'?out.width>maxWidth:out.height>maxHeight;if(!needed)continue;const next=trimVoidBorder(out,side);if(next){out=next;changed=true;break}}}return out}
function countKinds(level:SemanticLevel){const counts:Record<string,number>={};for(const row of level.tiles)for(const tile of row)counts[tile.kind]=(counts[tile.kind]??0)+1;return counts}
export function validateSemanticLevel(source:SemanticLevel,compressed:SemanticLevel=source):string[]{const errors:string[]=[];if(!compressed.tiles[compressed.playerStart.y]?.[compressed.playerStart.x])errors.push('start outside map');if(!compressed.tiles[compressed.goal.y]?.[compressed.goal.x])errors.push('goal outside map');const a=countKinds(source),b=countKinds(compressed);for(const kind of ['arrow','stone','wall','water','breakable','key','lock','teleport','bonus-time','start-marker','goal'])if((b[kind]??0)!==(a[kind]??0))errors.push(`required ${kind} count changed: ${a[kind]??0} -> ${b[kind]??0}`);return errors}
export function convertAndCompressLevel(id:number,grid:number[][],playerStart:{x:number;y:number},cavePos:{x:number;y:number}){const source=convertPhoneageLevel(id,grid,playerStart,cavePos);const compressed=compressSemanticLevel(source);const errors=validateSemanticLevel(source,compressed);if(errors.length)throw new Error(`Level ${id} rejected: ${errors.join('; ')}`);return compressed}
