export type Direction='up'|'right'|'down'|'left';
export type SemanticTile={kind:'void'}|{kind:'floor'}|{kind:'wall'}|{kind:'stone';height:number}|{kind:'breakable';height:number}|{kind:'goal'}|{kind:'start'}|{kind:'arrow';directions:Direction[]};
export type SemanticLevel={id:number;width:number;height:number;tiles:SemanticTile[][];playerStart:{x:number;y:number};goal:{x:number;y:number}};
const directions:Direction[]=['up','right','down','left'];
export function phoneageTileToSemantic(id:number):SemanticTile{switch(id){case 0:return{kind:'floor'};case 1:case 4:return{kind:'wall'};case 2:return{kind:'stone',height:1};case 3:return{kind:'goal'};case 5:return{kind:'void'};case 6:return{kind:'breakable',height:3};case 7:case 8:case 9:case 10:return{kind:'arrow',directions:[directions[id-7]]};case 11:return{kind:'arrow',directions:['up','down']};case 12:return{kind:'arrow',directions:['left','right']};case 13:return{kind:'arrow',directions:[...directions]};default:return{kind:'floor'}}}
export function convertPhoneageLevel(id:number,grid:number[][],playerStart:{x:number;y:number},cavePos:{x:number;y:number}):SemanticLevel{const height=grid.length,width=Math.max(0,...grid.map(r=>r.length));const tiles=grid.map(r=>Array.from({length:width},(_,x)=>phoneageTileToSemantic(r[x]??5)));if(tiles[playerStart.y]?.[playerStart.x])tiles[playerStart.y][playerStart.x]={kind:'start'};if(tiles[cavePos.y]?.[cavePos.x])tiles[cavePos.y][cavePos.x]={kind:'goal'};return{id,width,height,tiles,playerStart,goal:cavePos};}

function trimVoidBorder(level:SemanticLevel,side:'top'|'bottom'|'left'|'right'):SemanticLevel|null{const{tiles,width,height}=level;const removable=side==='top'?tiles[0].every(t=>t.kind==='void'):side==='bottom'?tiles[height-1].every(t=>t.kind==='void'):side==='left'?tiles.every(r=>r[0].kind==='void'):tiles.every(r=>r[width-1].kind==='void');if(!removable)return null;const dx=side==='left'?1:0,dy=side==='top'?1:0;const next=tiles.slice(dy,height-(side==='bottom'?1:0)).map(r=>r.slice(dx,width-(side==='right'?1:0)));return{...level,width:next[0]?.length??0,height:next.length,tiles:next,playerStart:{x:level.playerStart.x-dx,y:level.playerStart.y-dy},goal:{x:level.goal.x-dx,y:level.goal.y-dy}};}

/** Lossless compression: only removes completely void outer rows/columns. It never scales, remaps, or guesses cells. */
export function compressSemanticLevel(level:SemanticLevel,maxWidth=16,maxHeight=9):SemanticLevel{let out=level;let changed=true;while(changed&&(out.width>maxWidth||out.height>maxHeight)){changed=false;for(const side of ['top','bottom','left','right'] as const){if((out.width>maxWidth&&['left','right'].includes(side))||(out.height>maxHeight&&['top','bottom'].includes(side))){const next=trimVoidBorder(out,side);if(next){out=next;changed=true;break;}}}}return out;}

export function validateSemanticLevel(level:SemanticLevel):string[]{const errors:string[]=[];if(level.width>16||level.height>9)errors.push(`level remains ${level.width}x${level.height}; no safe void-only compression exists`);if(!level.tiles[level.playerStart.y]?.[level.playerStart.x])errors.push('start outside map');if(!level.tiles[level.goal.y]?.[level.goal.x])errors.push('goal outside map');let arrows=0,rocks=0;for(const row of level.tiles)for(const t of row){if(t.kind==='arrow')arrows++;if(t.kind==='stone'||t.kind==='breakable')rocks++;}if(arrows<0||rocks<0)errors.push('invalid object count');return errors;}
